### ISSUE TITLE
Importing polyfill directly does not work

### ISSUE THREAD

**Issue by 719media** [hufan-akari/seamless-scroll-polyfill#100]
In latest 1.2.1 version:

Works:
```
import { polyfill } from 'seamless-scroll-polyfill';
...
polyfill();
window.scrollTo({
  top: 0,
});
```

Does not work:
```
import { windowScrollTo } from 'seamless-scroll-polyfill';
...
windowScrollTo({
  top: 0,
});
```

**Comment by 719media** [comment]
This worked fine in 1.1.0 and 1.2.0, but broke in 1.2.1

**Comment by magic-akari** [comment]
Thanks!

**Comment by emilycritter** [comment]
I'm running into this issue in version 1.2.3 with importing `elementScrollIntoView`.

```
import { elementScrollIntoView } from 'seamless-scroll-polyfill';
...
elementScrollIntoView(el, { behavior: 'smooth' });
```

**Comment by liho00** [comment]
> I'm running into this issue in version 1.2.3 with importing `elementScrollIntoView`.
> 
> ```
> import { elementScrollIntoView } from 'seamless-scroll-polyfill';
> ...
> elementScrollIntoView(el, { behavior: 'smooth' });
> ```

same issue here, safari isnt working for elementScrollIntoView, im using latest version, pls help check

**Comment by magic-akari** [comment]
> > I'm running into this issue in version 1.2.3 with importing `elementScrollIntoView`.
> > ```
> > import { elementScrollIntoView } from 'seamless-scroll-polyfill';
> > ...
> > elementScrollIntoView(el, { behavior: 'smooth' });
> > ```
> 
> same issue here, safari isnt working for elementScrollIntoView, im using latest version, pls help check

Hi, what's the error message?

By the way, the `windowScroll` API changed since 2.0.
You should pass `window` as first argument.

**Comment by liho00** [comment]
> error

There is no error message, just does not scroll at all, but chrome is working fine

**Comment by liho00** [comment]
> > > I'm running into this issue in version 1.2.3 with importing `elementScrollIntoView`.
> > > ```
> > > import { elementScrollIntoView } from 'seamless-scroll-polyfill';
> > > ...
> > > elementScrollIntoView(el, { behavior: 'smooth' });
> > > ```
> > 
> > 
> > same issue here, safari isnt working for elementScrollIntoView, im using latest version, pls help check
> 
> Hi, what's the error message?
> 
> By the way, the `windowScroll` API changed since 2.0.
> You should pass `window` as first argument.

There is no error message, just does not scroll at all, but chrome is working fine, im using latest version

elementScrollIntoView should be using element  right, why passing window as first argument?

**Comment by magic-akari** [comment]
> > > > I'm running into this issue in version 1.2.3 with importing `elementScrollIntoView`.
> > > > ```
> > > > import { elementScrollIntoView } from 'seamless-scroll-polyfill';
> > > > ...
> > > > elementScrollIntoView(el, { behavior: 'smooth' });
> > > > ```
> > > 
> > > 
> > > same issue here, safari isnt working for elementScrollIntoView, im using latest version, pls help check
> > 
> > 
> > Hi, what's the error message?
> > By the way, the `windowScroll` API changed since 2.0.
> > You should pass `window` as first argument.
> 
> There is no error message, just does not scroll at all, but chrome is working fine, im using latest version
> 
> elementScrollIntoView should be using element right, why passing window as first argument?

Could you provide a code sandbox please? such as https://codesandbox.io/s/scrollintoview-iframe-zcwn0

**Comment by liho00** [comment]
> > > > > I'm running into this issue in version 1.2.3 with importing `elementScrollIntoView`.
> > > > > ```
> > > > > import { elementScrollIntoView } from 'seamless-scroll-polyfill';
> > > > > ...
> > > > > elementScrollIntoView(el, { behavior: 'smooth' });
> > > > > ```
> > > > 
> > > > 
> > > > same issue here, safari isnt working for elementScrollIntoView, im using latest version, pls help check
> > > 
> > > 
> > > Hi, what's the error message?
> > > By the way, the `windowScroll` API changed since 2.0.
> > > You should pass `window` as first argument.
> > 
> > 
> > There is no error message, just does not scroll at all, but chrome is working fine, im using latest version
> > elementScrollIntoView should be using element right, why passing window as first argument?
> 
> Could you provide a code sandbox please? such as https://codesandbox.io/s/scrollintoview-iframe-zcwn0

May be i know the reason, because im using vite js + vue3, do you plan to support vite js in future? https://vitejs.dev/

**Comment by magic-akari** [comment]
> > > > > > I'm running into this issue in version 1.2.3 with importing `elementScrollIntoView`.
> > > > > > ```
> > > > > > import { elementScrollIntoView } from 'seamless-scroll-polyfill';
> > > > > > ...
> > > > > > elementScrollIntoView(el, { behavior: 'smooth' });
> > > > > > ```
> > > > > 
> > > > > 
> > > > > same issue here, safari isnt working for elementScrollIntoView, im using latest version, pls help check
> > > > 
> > > > 
> > > > Hi, what's the error message?
> > > > By the way, the `windowScroll` API changed since 2.0.
> > > > You should pass `window` as first argument.
> > > 
> > > 
> > > There is no error message, just does not scroll at all, but chrome is working fine, im using latest version
> > > elementScrollIntoView should be using element right, why passing window as first argument?
> > 
> > 
> > Could you provide a code sandbox please? such as https://codesandbox.io/s/scrollintoview-iframe-zcwn0
> 
> May be i know the reason, because im using vite js + vue3, do you plan to support vite js in future? https://vitejs.dev/

I just tried Vite and Vue3 and everything seems to be OK.

The following is the simplest example.
[vite-project.zip](https://github.com/magic-akari/seamless-scroll-polyfill/files/7155154/vite-project.zip)
