### ISSUE TITLE
Where to put import?

### ISSUE THREAD

**Issue by coler-j** [hufan-akari/seamless-scroll-polyfill#105]
Should be import of the polyfill be at some top level outside the mounting of the react application? Or can it be directly inside my functional component?

**Comment by magic-akari** [comment]
Sorry for the late update. Notification has been flooded so heavily.

Yes, you can import the polyfill function and call it once at the top level.
Or, you can import and call the specific function you need.

**Comment by magic-akari** [comment]
I cannot figure out why bot commented here. I will close this issue.
