### ISSUE TITLE
Reference to document causes GatsbyJS build to fail

### ISSUE THREAD

**Issue by alandickinson** [hufan-akari/seamless-scroll-polyfill#108]
Hi again! I'm using this polyfill in a [Gatsby](https://gatsbyjs.com) project, which supports server side rendering. So the code runs outside of a browser, and [doesn't have access to the document or window objects](https://www.gatsbyjs.com/docs/debugging-html-builds/). This line is causing gatsby builds to fail because it references the document object without checking first if it exists:
https://github.com/magic-akari/seamless-scroll-polyfill/blob/5d7f8b61896671f8b684d03bf8fa563a5127eca3/src/common.ts#L7

**Comment by alandickinson** [comment]
I've solved this in my project for now by checking that window is defined before running any of the polyfill code. 

```js
typeof window !== 'undefined' && elementScrollIntoViewPolyfill();
```
```js
if (typeof window !== 'undefined') {
    tabRefs.current[index].scrollIntoView({
        behavior: "smooth",
        inline: "center",
        block: "nearest",
        // set a custom duration used by the polyfill
        duration: 150
    });
}
```

**Comment by magic-akari** [comment]
All the code is side-effect free(except auto-polyfill.js). You can import it safely. 
But before calling the polyfill function, you have to make sure the code runs in browser.

Example:

```js
if(isBrowser()){
  elementScrollIntoViewPolyfill();
}
```
