### ISSUE TITLE
elementScrollIntoView() breaks in an iframe

### ISSUE THREAD

**Issue by dakur** [hufan-akari/seamless-scroll-polyfill#118]
Version: 1.2.4 / 2.0.0

If I use "[Use method directly without patching](https://github.com/magic-akari/seamless-scroll-polyfill#use-methods-directly-without-patching)" scenario:

```js
import { elementScrollIntoView } from "seamless-scroll-polyfill";

elementScrollIntoView(someElement, {behavior: "smooth"});
```

and the element is in an iframe, it breaks on [this line](https://github.com/magic-akari/seamless-scroll-polyfill/blob/v1.2.4/src/Element.scrollIntoView.ts#L400) with `TypeError: Argument 1 ('element') to Window.getComputedStyle must be an instance of Element getComputedStyle`

I've tried to debug it and found out that in the for-loop, it resolves parents as follows:
- `<body>` – OK
- `<html>` – OK
- `#document` – throws the error

There is probably some condition missing for iframe cases…

**Comment by magic-akari** [comment]
Hi,
Could you try the [2.0.1 version](https://www.npmjs.com/package/seamless-scroll-polyfill/v/2.0.1) ?
feedback welcome.

**Comment by dakur** [comment]
@magic-akari Yes, that works. Thank you very much!

By the way, 2.0.x versions are not on npm, I had to install it with `@next`.
