### ISSUE TITLE
`{block: 'nearest'}` doesn't work properly when the target is hidden below bottom edge

### ISSUE THREAD

**Issue by dakur** [hufan-akari/seamless-scroll-polyfill#126]
Neither in standard document, nor in an iframe – though it's consistent in how it's wrong – in both cases the target element becomes hidden above top edge of the current window element instead of being sticked to the bottom of it. Looks like height of the window element has been forgotten to take into consideration.

See an example: https://codesandbox.io/s/festive-cookies-ogk06 – try to click the button at the top and at the bottom

**Comment by magic-akari** [comment]
Thanks!

**Comment by dakur** [comment]
Thank you – for the fix!
