### ISSUE TITLE
Logical OR Assignment (`||=`) in v2 Causing Browser Compatibility Issues

### ISSUE THREAD

**Issue by mutewinter** [hufan-akari/seamless-scroll-polyfill#128]
When moving from v1 to v2, I noticed our build output now contains this line:

```
proto[backup] ||= proto[method];
```
Located in: `node_modules/seamless-scroll-polyfill/lib/common.js`

This is causing issues for some of our users who have browsers that don't support this operator.

I haven't been able to figure out why this isn't transpiled by Babel, where v1 works just fine. I'm assuming it's because of this change from v2:

> The output format is only esm(es2021 syntax + es5 lib) and umd

I tried adding https://babeljs.io/docs/en/babel-plugin-proposal-logical-assignment-operators, but that didn't resolve it (and I strongly suspect this is already being run on our codebase via @babel/preset-env.

I verified this issue is only present in v2.

**Comment by magic-akari** [comment]
sorry for the late reply.

The version 2.1.5 change output target to es2020 and removed `logical or assignment`.
If you still encounter similar problems, try transpile this library in your toolchain or use the UMD version.

**Comment by mutewinter** [comment]
Not late at all. Appreciate the fix!
