### ISSUE TITLE
Functions not importable anymore starting at 2.1.7

### ISSUE THREAD

**Issue by coehne** [hufan-akari/seamless-scroll-polyfill#134]
Hi, with versions 2.1.7 and above I get the following error when I want to import it:
"Attempted import error: 'polyfill' is not exported from 'seamless-scroll-polyfill'"

This is also true for "scrollIntoView" and "elementScrollIntoViewPolyfill"

Version 2.1.6 is working for me.

Using React 17, Yarn and Typescript 4.6

What other information can I provide to help finding the cause?

**Comment by magic-akari** [comment]
The `.cjs` suffix was used in 2.1.7 to bypass the next.js issue.
Check to see if your toolchain doesn't support the `.cjs` suffix.

- https://github.com/magic-akari/seamless-scroll-polyfill/compare/v2.1.6..v2.1.7
- #131
