### ISSUE TITLE
Can I add offset to scrollIntoView?

### ISSUE THREAD

**Issue by ggukggukee** [hufan-akari/seamless-scroll-polyfill#138]
Is any chance that I can add offset to scrollIntoView function?

**Comment by magic-akari** [comment]
Yes, you can use [scroll-margin 🔗](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin).

https://github.com/magic-akari/seamless-scroll-polyfill/blob/71e9234b548531e196d4031186c78947f4de7f80/src/scrollIntoView.ts#L376-L398
