### ISSUE TITLE
Parameterless call of scrollIntoView not working as intended

### ISSUE THREAD

**Issue by anwerso** [hufan-akari/seamless-scroll-polyfill#141]
`scrollIntoView()` without parameters not working right when you use `scroll-margin/scroll-snap-margin` to adjust scrolling position. The workaround is to add an empty object. The culprit is [the check to use original prototype](https://github.com/magic-akari/seamless-scroll-polyfill/blob/master/src/scrollIntoView.polyfill.ts#L23) when there are no params. As a solution we can always convert params to a new format and use polyfilled version.

**Comment by magic-akari** [comment]
The primary purpose of this polyfill is to patch the 'smooth' function. The detection of 'scroll-snap-margin' is necessary for compliance with the specifications. 

Additionally, it assumes the other features, such as 'scroll-snap-margin', to be functioning as intended.\
Therefore, when the parameters are not set to 'smooth', the polyfill will directly call the native method.
