### ISSUE TITLE
Types break with moduleResolution NodeNext in tsconfig.json

### ISSUE THREAD

**Issue by unshame** [hufan-akari/seamless-scroll-polyfill#144]
With `"moduleResolution": "NodeNext"` in `tsconfig.json`, typescript fails to find type definitions for `seamless-scroll-polyfill`.

This is caused by the following issues:

1. Lack of `"types": "./lib/index.d.ts"` **under `exports`** in package.json. Typescript ignores the root `"types"` in this mode.
2. Type imports without file extension in source code and compiled code, i.e. https://github.com/magic-akari/seamless-scroll-polyfill/blob/master/src/scroll.ts#L11 Since this package is specified as `"type": "module"` in `package.json`, typescript uses esm path resolution in this mode.

**Comment by magic-akari** [comment]
There is still an issue with the `"moduleResolution": "NodeNext"` and `"type":"commonjs"` option.

- ref ：https://github.com/microsoft/TypeScript/issues/50466
