### ISSUE TITLE
block: "nearest" does not work if the element is the same height as the container

### ISSUE THREAD

**Issue by jonom** [hufan-akari/seamless-scroll-polyfill#75]
If an element has the same height as the window (e.g. an element with height of 100vh) then 
```js
element.scrollIntoView({
    behavior: "smooth",
    block: "nearest"
});
```
has no effect.

**Comment by jonom** [comment]
Wow, that was a fast response! I was going to try to fix this today but you already did it 😄 thanks so much.

**Comment by magic-akari** [comment]
I forget to fix the same issue about `inline "nearest"`.
The current code is a bit confusing.
May be fixed at the next refactoring.
