### ISSUE TITLE
TypeError: Can only call Performance.now on instances of Performance

### ISSUE THREAD

**Issue by stami** [hufan-akari/seamless-scroll-polyfill#81]
Hi, the latest version breaks on Safari browsers, and probably all others where the polyfill is used.

In the last [commit](https://github.com/magic-akari/seamless-scroll-polyfill/commit/19fa082567eadfdc5c286b74c5d0b417829f7aca), the optional chaining will probably be transpiled to some equivalent of the following example, that can be replicated in Safari console:
```
> performance.now()
// prints out the value

const myNow = performance.now
myNow()
// TypeError: Can only call Performance.now on instances of Performance
```

It crashes also on Chrome console with `TypeError: Illegal invocation`, but the polyfill won't get applied on Chrome...

The original pull request line runs fine as is: 
```
(performance && performance.now ? performance : Date).now();
```

**Comment by magic-akari** [comment]
My bad. Thanks.
