### ISSUE TITLE
window.scrollTo with behavior: 'smooth' doesn't scroll to the top of the page with safari 

### ISSUE THREAD

**Issue by ieozt38** [hufan-akari/seamless-scroll-polyfill#93]
On Safari code below doesn't scroll to the top of the page however on other browsers it does. When I delete smooth-scrolling, it scrolls back to the top. (Angular 10) script added in index.html.

       window.scrollTo({
          behavior: 'smooth',
          top: 0,
          left: 0,
        });

**Comment by 719media** [comment]
if the latest version as of this writing, if I do
```
import { windowScrollTo } from 'seamless-scroll-polyfill';
...
windowScrollTo({
  top: 0,
});
```
in chrome it doesn't do anything, no errors either

**Comment by 719media** [comment]
May be related: #100
