### ISSUE TITLE
Arrow function prevents this to work in IE11

### ISSUE THREAD

**Issue by lfuelling** [hufan-akari/seamless-scroll-polyfill#99]
Hi, 

I'm trying to use this polyfill in IE11 and get syntax errors because there is an arrow function in the code and IE11 doesn't support those. 

I might create a PR for this in the next few hours.

**Comment by lfuelling** [comment]
To anyone having the same problem:

You can simply replace `import('seamless-scroll-polyfill')` with `import('seamless-scroll-polyfill/dist/es5/seamless.js')` to use the ES5 version.

**Comment by magic-akari** [comment]
Hello,

```json
    "main": "dist/es5/seamless.js",
    "umd:main": "dist/umd/index.js",
    "module": "dist/esm/index.js",
```

In the `package.json`, the main field is target to es5 dist.
And the umd dist is in es2018 format.
Would you mind to provide the scaffold settings such as webpack.config.js?

**Comment by lfuelling** [comment]
Hi,
in my case (using parcel) the `module` field is imported, not the `main` field. 
But it works just as well with the explicit import mentioned above.
